name = "GradedArrays"
uuid = "bc96ca6e-b7c8-4bb6-888e-c93f838762c2"
version = "0.6.3"
authors = ["ITensor developers <support@itensor.org> and contributors"]

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]

[deps]
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
BlockSparseArrays = "2c9a651f-6452-4ace-a6ac-809f4280fbb4"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
HalfIntegers = "f0d1745a-41c9-11e9-1dd9-e5d34d218721"
KroneckerArrays = "05d0b138-81bc-4ff7-84be-08becefb1ccc"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixAlgebraKit = "6c742aac-3347-4629-af66-fc926824e5e4"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArraysBase = "0d5efcca-f356-4864-8770-e1ed8d78f208"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
TensorAlgebra = "68bd88dc-f39d-4e12-b2ca-f046b68fcc6a"
TensorKitSectors = "13a9c161-d5da-41f0-bcbd-e1a08ae0647f"
TypeParameterAccessors = "7e5a90cf-f82e-492e-a09b-e3e26432c138"

[weakdeps]
NamedDimsArrays = "60cbd0c0-df58-4cb7-918c-6f5607b73fde"
SUNRepresentations = "1a50b95c-7aac-476d-a9ce-2bfc675fc617"

[extensions]
GradedArraysNamedDimsArraysExt = "NamedDimsArrays"
GradedArraysSUNRepresentationsExt = "SUNRepresentations"

[compat]
ArrayLayouts = "1"
BlockArrays = "1.6"
BlockSparseArrays = "0.10"
Compat = "4.16"
FillArrays = "1.13"
HalfIntegers = "1.6"
KroneckerArrays = "0.3"
LinearAlgebra = "1.10"
MatrixAlgebraKit = "0.6"
NamedDimsArrays = "0.13, 0.14"
Random = "1.10"
SUNRepresentations = "0.3"
SparseArraysBase = "0.9"
SplitApplyCombine = "1.2.3"
TensorAlgebra = "0.6, 0.7"
TensorKitSectors = "0.3"
TypeParameterAccessors = "0.4"
julia = "1.10"
